// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MmsMembersColumns holds the columns for the "mms_members" table.
	MmsMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Default: 1},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "nickname", Type: field.TypeString, Unique: true},
		{Name: "mobile", Type: field.TypeString, Nullable: true},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "avatar", Type: field.TypeString, Nullable: true, Default: "", SchemaType: map[string]string{"mysql": "varchar(512)"}},
		{Name: "rank_id", Type: field.TypeUint64, Nullable: true, Default: 2},
	}
	// MmsMembersTable holds the schema information for the "mms_members" table.
	MmsMembersTable = &schema.Table{
		Name:       "mms_members",
		Columns:    MmsMembersColumns,
		PrimaryKey: []*schema.Column{MmsMembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "mms_members_mms_ranks_ranks",
				Columns:    []*schema.Column{MmsMembersColumns[10]},
				RefColumns: []*schema.Column{MmsRanksColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "member_username_email",
				Unique:  true,
				Columns: []*schema.Column{MmsMembersColumns[4], MmsMembersColumns[8]},
			},
		},
	}
	// MmsRanksColumns holds the columns for the "mms_ranks" table.
	MmsRanksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "code", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "remark", Type: field.TypeString},
	}
	// MmsRanksTable holds the schema information for the "mms_ranks" table.
	MmsRanksTable = &schema.Table{
		Name:       "mms_ranks",
		Columns:    MmsRanksColumns,
		PrimaryKey: []*schema.Column{MmsRanksColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MmsMembersTable,
		MmsRanksTable,
	}
)

func init() {
	MmsMembersTable.ForeignKeys[0].RefTable = MmsRanksTable
	MmsMembersTable.Annotation = &entsql.Annotation{
		Table: "mms_members",
	}
	MmsRanksTable.Annotation = &entsql.Annotation{
		Table: "mms_ranks",
	}
}
