// Code generated by ent, DO NOT EDIT.

package ent

// set field if value is not empty. e.g. string does not equal to ""
func (m *MemberUpdate) SetNotEmptyStatus(value uint8) *MemberUpdate {
	if value != 0 {
		return m.SetStatus(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MemberUpdateOne) SetNotEmptyStatus(value uint8) *MemberUpdateOne {
	if value != 0 {
		return m.SetStatus(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MemberUpdate) SetNotEmptyUsername(value string) *MemberUpdate {
	if value != "" {
		return m.SetUsername(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MemberUpdateOne) SetNotEmptyUsername(value string) *MemberUpdateOne {
	if value != "" {
		return m.SetUsername(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MemberUpdate) SetNotEmptyPassword(value string) *MemberUpdate {
	if value != "" {
		return m.SetPassword(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MemberUpdateOne) SetNotEmptyPassword(value string) *MemberUpdateOne {
	if value != "" {
		return m.SetPassword(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MemberUpdate) SetNotEmptyNickname(value string) *MemberUpdate {
	if value != "" {
		return m.SetNickname(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MemberUpdateOne) SetNotEmptyNickname(value string) *MemberUpdateOne {
	if value != "" {
		return m.SetNickname(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MemberUpdate) SetNotEmptyRankID(value uint64) *MemberUpdate {
	if value != 0 {
		return m.SetRankID(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MemberUpdateOne) SetNotEmptyRankID(value uint64) *MemberUpdateOne {
	if value != 0 {
		return m.SetRankID(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MemberUpdate) SetNotEmptyMobile(value string) *MemberUpdate {
	if value != "" {
		return m.SetMobile(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MemberUpdateOne) SetNotEmptyMobile(value string) *MemberUpdateOne {
	if value != "" {
		return m.SetMobile(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MemberUpdate) SetNotEmptyEmail(value string) *MemberUpdate {
	if value != "" {
		return m.SetEmail(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MemberUpdateOne) SetNotEmptyEmail(value string) *MemberUpdateOne {
	if value != "" {
		return m.SetEmail(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MemberUpdate) SetNotEmptyAvatar(value string) *MemberUpdate {
	if value != "" {
		return m.SetAvatar(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MemberUpdateOne) SetNotEmptyAvatar(value string) *MemberUpdateOne {
	if value != "" {
		return m.SetAvatar(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (mr *MemberRankUpdate) SetNotEmptyName(value string) *MemberRankUpdate {
	if value != "" {
		return mr.SetName(value)
	}
	return mr
}

// set field if value is not empty. e.g. string does not equal to ""
func (mr *MemberRankUpdateOne) SetNotEmptyName(value string) *MemberRankUpdateOne {
	if value != "" {
		return mr.SetName(value)
	}
	return mr
}

// set field if value is not empty. e.g. string does not equal to ""
func (mr *MemberRankUpdate) SetNotEmptyCode(value string) *MemberRankUpdate {
	if value != "" {
		return mr.SetCode(value)
	}
	return mr
}

// set field if value is not empty. e.g. string does not equal to ""
func (mr *MemberRankUpdateOne) SetNotEmptyCode(value string) *MemberRankUpdateOne {
	if value != "" {
		return mr.SetCode(value)
	}
	return mr
}

// set field if value is not empty. e.g. string does not equal to ""
func (mr *MemberRankUpdate) SetNotEmptyDescription(value string) *MemberRankUpdate {
	if value != "" {
		return mr.SetDescription(value)
	}
	return mr
}

// set field if value is not empty. e.g. string does not equal to ""
func (mr *MemberRankUpdateOne) SetNotEmptyDescription(value string) *MemberRankUpdateOne {
	if value != "" {
		return mr.SetDescription(value)
	}
	return mr
}

// set field if value is not empty. e.g. string does not equal to ""
func (mr *MemberRankUpdate) SetNotEmptyRemark(value string) *MemberRankUpdate {
	if value != "" {
		return mr.SetRemark(value)
	}
	return mr
}

// set field if value is not empty. e.g. string does not equal to ""
func (mr *MemberRankUpdateOne) SetNotEmptyRemark(value string) *MemberRankUpdateOne {
	if value != "" {
		return mr.SetRemark(value)
	}
	return mr
}
