// Code generated by ent, DO NOT EDIT.

package ent

import "time"

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilUpdatedAt(value *time.Time) *MemberUpdate {
	if value != nil {
		return m.SetUpdatedAt(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilUpdatedAt(value *time.Time) *MemberUpdateOne {
	if value != nil {
		return m.SetUpdatedAt(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilUpdatedAt(value *time.Time) *MemberCreate {
	if value != nil {
		return m.SetUpdatedAt(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilStatus(value *uint8) *MemberUpdate {
	if value != nil {
		return m.SetStatus(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilStatus(value *uint8) *MemberUpdateOne {
	if value != nil {
		return m.SetStatus(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilStatus(value *uint8) *MemberCreate {
	if value != nil {
		return m.SetStatus(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilUsername(value *string) *MemberUpdate {
	if value != nil {
		return m.SetUsername(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilUsername(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetUsername(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilUsername(value *string) *MemberCreate {
	if value != nil {
		return m.SetUsername(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilPassword(value *string) *MemberUpdate {
	if value != nil {
		return m.SetPassword(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilPassword(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetPassword(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilPassword(value *string) *MemberCreate {
	if value != nil {
		return m.SetPassword(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilNickname(value *string) *MemberUpdate {
	if value != nil {
		return m.SetNickname(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilNickname(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetNickname(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilNickname(value *string) *MemberCreate {
	if value != nil {
		return m.SetNickname(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilRankID(value *uint64) *MemberUpdate {
	if value != nil {
		return m.SetRankID(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilRankID(value *uint64) *MemberUpdateOne {
	if value != nil {
		return m.SetRankID(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilRankID(value *uint64) *MemberCreate {
	if value != nil {
		return m.SetRankID(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilMobile(value *string) *MemberUpdate {
	if value != nil {
		return m.SetMobile(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilMobile(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetMobile(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilMobile(value *string) *MemberCreate {
	if value != nil {
		return m.SetMobile(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilEmail(value *string) *MemberUpdate {
	if value != nil {
		return m.SetEmail(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilEmail(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetEmail(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilEmail(value *string) *MemberCreate {
	if value != nil {
		return m.SetEmail(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilAvatar(value *string) *MemberUpdate {
	if value != nil {
		return m.SetAvatar(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilAvatar(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetAvatar(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilAvatar(value *string) *MemberCreate {
	if value != nil {
		return m.SetAvatar(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdate) SetNotNilUpdatedAt(value *time.Time) *MemberRankUpdate {
	if value != nil {
		return mr.SetUpdatedAt(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdateOne) SetNotNilUpdatedAt(value *time.Time) *MemberRankUpdateOne {
	if value != nil {
		return mr.SetUpdatedAt(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankCreate) SetNotNilUpdatedAt(value *time.Time) *MemberRankCreate {
	if value != nil {
		return mr.SetUpdatedAt(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdate) SetNotNilName(value *string) *MemberRankUpdate {
	if value != nil {
		return mr.SetName(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdateOne) SetNotNilName(value *string) *MemberRankUpdateOne {
	if value != nil {
		return mr.SetName(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankCreate) SetNotNilName(value *string) *MemberRankCreate {
	if value != nil {
		return mr.SetName(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdate) SetNotNilCode(value *string) *MemberRankUpdate {
	if value != nil {
		return mr.SetCode(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdateOne) SetNotNilCode(value *string) *MemberRankUpdateOne {
	if value != nil {
		return mr.SetCode(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankCreate) SetNotNilCode(value *string) *MemberRankCreate {
	if value != nil {
		return mr.SetCode(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdate) SetNotNilDescription(value *string) *MemberRankUpdate {
	if value != nil {
		return mr.SetDescription(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdateOne) SetNotNilDescription(value *string) *MemberRankUpdateOne {
	if value != nil {
		return mr.SetDescription(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankCreate) SetNotNilDescription(value *string) *MemberRankCreate {
	if value != nil {
		return mr.SetDescription(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdate) SetNotNilRemark(value *string) *MemberRankUpdate {
	if value != nil {
		return mr.SetRemark(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdateOne) SetNotNilRemark(value *string) *MemberRankUpdateOne {
	if value != nil {
		return mr.SetRemark(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankCreate) SetNotNilRemark(value *string) *MemberRankCreate {
	if value != nil {
		return mr.SetRemark(*value)
	}
	return mr
}
